### ISSUE TITLE
Blog Item no longer visible

### ISSUE THREAD

**Issue by jeremycherfas** [getgrav/grav-theme-antimatter#104]
Since updating to Antimatter 2.1.1 I no longer see the Blog Item tab when editing a blog page. No idea why this might be. 

`/user/themes/antimatter/blueprints/item.yaml`is present and starts with 

````
title: Item
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:

      fields:
        blog:
          type: tab
          title: Blog Item
````

But nothing shows up when editing a page.
