### ISSUE TITLE
template.css overrides header elements with negative letter-spacing

### ISSUE THREAD

**Issue by leagris** [getgrav/grav-theme-antimatter#105]
`template.css` overrides header elements `h1`, `h2`, `h3` with negative letter-spacing.
It is an issue when incorporating title elements from foreign sources as it makes titles illegibles.

[css-compiled/template.css Lines 232 to 340](https://github.com/getgrav/grav-theme-antimatter/blob/develop/css-compiled/template.css#L332-L340)
```CSS
h1 {
  text-align: center;
  letter-spacing: -3px; }

h2 {
  letter-spacing: -2px; }

h3 {
  letter-spacing: -1px; }
```
