### ISSUE TITLE
Taxonomy page collection not valid when using blog template

### ISSUE THREAD

**Issue by jleeong** [getgrav/grav-theme-antimatter#108]
Attempting to create a taxonomy page collection leads to "Validation failed: Invalid input in "Items"" when editing from the admin console

Frontmatter:
```
content:
    items:
        '@taxonomy.tag': testing
    limit: 5
```
