### ISSUE TITLE
< and > cause twig exception with summary and on a short published blog item

### ISSUE THREAD

**Issue by Reedicht** [getgrav/grav-theme-antimatter#37]
When creating a blog item under a blog that is short (shorter than the summary length?), that includes less than and greater than symbols, and a summary is enabled causes the following Twig runtime exception:

```
An exception has been thrown during the rendering of a template ("DOMDocumentFragment::appendXML(): Entity: line 1: parser error : Premature end of data in tag user line 1") in "partials/blog_item.html.twig" at line 50.
```

For instance, the following causes an error by itself with summary enabled:

    admin add <user>

Disabling the summary on the blog item fixes this.

Additionally, adding the above to a larger blog item (larger than the summary length?) does not cause the issue.

**Comment by flaviocopes** [comment]
Can you attach a complete post md file example that can recreate the issue?

**Comment by Reedicht** [comment]
Sure. This is a test item.md that seems to cause the issue

```
---
title: 'Test Page 2'
external_links:
    process: true
    title: false
    no_follow: true
    mode: active
    target: _blank
summary:
    enabled: '1'
    format: short
---

    admin add <user>
```
