### ISSUE TITLE
Multisite configuration

### ISSUE THREAD

**Issue by hotovec** [getgrav/grav-theme-antimatter#41]
antimatter.yaml

```
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      paths:
        - user/themes/antimatter
```

these lines causing issue when you trying configure multisite config.
https://github.com/getgrav/grav/issues/627
